package xmaswishlist;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * XmasWishlistGUI.java
 * 08/01/2022
 * @author Christopher Tobaras, x20324573
 * 
 */
public class XmasWishlistGUI extends javax.swing.JFrame {
    private ArrayList <Gifts> wishlist;

    /**
     * Creates new form XmasWishlistGUI
     */
    public XmasWishlistGUI() {
        wishlist = new ArrayList<>();
        initComponents();
        typeLBL.setVisible(false);
        brandLBL.setVisible(false);
        colourLBL.setVisible(false);
        typeTF.setVisible(false);
        brandTF.setVisible(false);
        colourTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giftTypeGRP = new javax.swing.ButtonGroup();
        headerLBL = new javax.swing.JLabel();
        boardGameRB = new javax.swing.JRadioButton();
        craftSuppliesRB = new javax.swing.JRadioButton();
        toysRB = new javax.swing.JRadioButton();
        itemNumberLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        priceLBL = new javax.swing.JLabel();
        URLLBL = new javax.swing.JLabel();
        descriptionLBL = new javax.swing.JLabel();
        typeLBL = new javax.swing.JLabel();
        publisherLBL = new javax.swing.JLabel();
        brandLBL = new javax.swing.JLabel();
        colourLBL = new javax.swing.JLabel();
        itemNumberTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        URLTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        typeTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        publisherTF = new javax.swing.JTextField();
        brandTF = new javax.swing.JTextField();
        colourTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        loadBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        randomBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLBL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        headerLBL.setText("Christmas Wish List Tracker!");

        giftTypeGRP.add(boardGameRB);
        boardGameRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boardGameRB.setSelected(true);
        boardGameRB.setText("Board Game");
        boardGameRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardGameRBActionPerformed(evt);
            }
        });

        giftTypeGRP.add(craftSuppliesRB);
        craftSuppliesRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        craftSuppliesRB.setText("Craft Supplies");
        craftSuppliesRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                craftSuppliesRBActionPerformed(evt);
            }
        });

        giftTypeGRP.add(toysRB);
        toysRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        toysRB.setText("Toys");
        toysRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toysRBActionPerformed(evt);
            }
        });

        itemNumberLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        itemNumberLBL.setText("Item Number:");

        nameLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLBL.setText("Name:");

        priceLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        priceLBL.setText("Price:");

        URLLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        URLLBL.setText("URL:");

        descriptionLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        descriptionLBL.setText("Description:");

        typeLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        typeLBL.setText("Type:");

        publisherLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        publisherLBL.setText("Publisher:");

        brandLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brandLBL.setText("Brand:");

        colourLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        colourLBL.setText("Colour:");

        itemNumberTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        priceTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        URLTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        typeTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        descriptionTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        publisherTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        brandTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        colourTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        addBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        displayBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        searchBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        jLabel11.setText("Author: Christopher Tobaras");

        loadBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loadBTN.setText("Load");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        deleteBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        randomBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        randomBTN.setText("Random");
        randomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(headerLBL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(priceLBL)
                                .addComponent(URLLBL))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(URLTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(itemNumberLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(itemNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(typeLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(descriptionLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(nameLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colourLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(publisherLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(publisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(craftSuppliesRB)
                            .addComponent(toysRB)
                            .addComponent(boardGameRB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(displayBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBTN)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(randomBTN)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLBL)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNumberLBL)
                            .addComponent(itemNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(URLLBL)
                            .addComponent(URLTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boardGameRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(craftSuppliesRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toysRB)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBTN)
                            .addComponent(searchBTN))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayBTN)
                            .addComponent(deleteBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBTN)
                            .addComponent(loadBTN))
                        .addGap(18, 18, 18)
                        .addComponent(randomBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLBL)
                            .addComponent(typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionLBL)
                            .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brandLBL)
                            .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colourLBL)
                            .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardGameRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardGameRBActionPerformed
        // TODO add your handling code here:
        typeLBL.setVisible(false);
        typeTF.setVisible(false);
        brandLBL.setVisible(false);
        brandTF.setVisible(false);
        colourLBL.setVisible(false);
        colourTF.setVisible(false);
        
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        publisherLBL.setVisible(true);
        publisherTF.setVisible(true);
    }//GEN-LAST:event_boardGameRBActionPerformed

    private void craftSuppliesRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_craftSuppliesRBActionPerformed
        // TODO add your handling code here:

        nameLBL.setVisible(false);
        nameTF.setVisible(false);
        publisherLBL.setVisible(false);
        publisherTF.setVisible(false);
        
        typeLBL.setVisible(true);
        typeTF.setVisible(true);
        brandLBL.setVisible(true);
        brandTF.setVisible(true);        
        colourLBL.setVisible(true);
        colourTF.setVisible(true);        
    }//GEN-LAST:event_craftSuppliesRBActionPerformed

    private void toysRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toysRBActionPerformed
        // TODO add your handling code here:
        publisherLBL.setVisible(false);
        publisherTF.setVisible(false);
        brandLBL.setVisible(false);
        brandTF.setVisible(false);
        colourLBL.setVisible(false);
        colourTF.setVisible(false);
        
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        typeLBL.setVisible(true);
        typeTF.setVisible(true);
    }//GEN-LAST:event_toysRBActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        if(boardGameRB.isSelected()){
            BoardGame bg = new BoardGame(
            Integer.parseInt(itemNumberTF.getText()),
            descriptionTF.getText(),
            Integer.parseInt(priceTF.getText()),
            URLTF.getText(),
            nameTF.getText(),
            publisherTF.getText()
            );
            wishlist.add(bg);
        }
        
        if(craftSuppliesRB.isSelected()){
            CraftSupplies cs = new CraftSupplies(
            Integer.parseInt(itemNumberTF.getText()),
            descriptionTF.getText(),
            Integer.parseInt(priceTF.getText()),
            URLTF.getText(),
            typeTF.getText(),
            brandTF.getText(),
            colourTF.getText()
            );
            wishlist.add(cs);
        }
        
        if(toysRB.isSelected()){
            Toys t = new Toys(
            Integer.parseInt(itemNumberTF.getText()),
            descriptionTF.getText(),
            Integer.parseInt(priceTF.getText()),
            URLTF.getText(),
            nameTF.getText(),
            typeTF.getText()
            );
            wishlist.add(t);
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < wishlist.size();i++){
            Gifts g = wishlist.get(i);
            JOptionPane.showMessageDialog(null, g.printDetails());
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        boolean isFound = false;
        if(wishlist.isEmpty()){
            JOptionPane.showMessageDialog(null,"There are no entries!");
        }
        else{
            int searchTerm = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter an item number: "));
            for(Gifts g:wishlist){
                if(g.getItemNo() == searchTerm){
                    JOptionPane.showMessageDialog(null, g.printDetails());
                    isFound = true;
                }
            }
            if(isFound == false){
                JOptionPane.showMessageDialog(null, "Your search query found no results!");
            }            
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File("XmasWishlist.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(wishlist);
            oStream.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Unable to save!\n"+e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("XmasWishlist.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            wishlist = (ArrayList<Gifts>)oStream.readObject();
            oStream.close();
        }
        catch(IOException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Unable to load!\n"+e);
        }
        
    }//GEN-LAST:event_loadBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        boolean isFound = false;
        if(wishlist.isEmpty()){
            JOptionPane.showMessageDialog(null,"There are no entries to delete!");
        }
        else{
            int searchTerm = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter an item number to delete: "));
            for(int i = 0; i < wishlist.size();i++){
                if(wishlist.get(i).getItemNo() == searchTerm){
                    wishlist.remove(wishlist.get(i));
                    JOptionPane.showMessageDialog(null, "Item Successfully Deleted!");
                    isFound = true;
                }
            }
            if(isFound == false){
                JOptionPane.showMessageDialog(null, "We could not find the entry you would like to delete");
            }            
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void randomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBTNActionPerformed
        int randInt = (int)(Math.random() * wishlist.size());
        Gifts g = wishlist.get(randInt);
        JOptionPane.showMessageDialog(null, g.printDetails());
    }//GEN-LAST:event_randomBTNActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel URLLBL;
    private javax.swing.JTextField URLTF;
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton boardGameRB;
    private javax.swing.JLabel brandLBL;
    private javax.swing.JTextField brandTF;
    private javax.swing.JLabel colourLBL;
    private javax.swing.JTextField colourTF;
    private javax.swing.JRadioButton craftSuppliesRB;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel descriptionLBL;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JButton displayBTN;
    private javax.swing.ButtonGroup giftTypeGRP;
    private javax.swing.JLabel headerLBL;
    private javax.swing.JLabel itemNumberLBL;
    private javax.swing.JTextField itemNumberTF;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JButton loadBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel priceLBL;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel publisherLBL;
    private javax.swing.JTextField publisherTF;
    private javax.swing.JButton randomBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JRadioButton toysRB;
    private javax.swing.JLabel typeLBL;
    private javax.swing.JTextField typeTF;
    // End of variables declaration//GEN-END:variables
}
